[workspace]
resolver = "2"
members = [
    "crates/renderer",
    "crates/renderer-android",
    "crates/renderer-desktop",
    "crates/renderer-web",
]

[workspace.dependencies]
bytemuck = { version = "1", features = ["derive"] }
glam = "0.29"
gltf = { version = "1", features = ["import"] }
image = "0.25"
log = "0.4"
pollster = "0.3"
tobj = "4"
wgpu = { version = "22.1", features = ["webgl"] }
winit = "0.30"
egui = "0.29"
egui-wgpu = "0.29"
egui_plot = "0.29"
egui-winit = { version = "0.29", default-features = false }
binrw = "0.14"
modular-bitfield = "0.11"
wasm-bindgen-futures = "0.4"

env_logger = "0.11"
rfd = "0.15"
