[package]
name = "renderer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytemuck.workspace = true
glam.workspace = true
gltf.workspace = true
image.workspace = true
log.workspace = true
tobj.workspace = true
wgpu.workspace = true
winit.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui_plot.workspace = true
egui-winit.workspace = true
binrw.workspace = true
modular-bitfield.workspace = true

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64")))'.dependencies]
pollster.workspace = true

[target.'cfg(any(target_arch = "wasm32", target_arch = "wasm64"))'.dependencies]
wasm-bindgen-futures.workspace = true
