[package]
name = "renderer-desktop"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
renderer = { path = "../renderer", features = ["winit", "tokio-transport"] }
env_logger.workspace = true
