name: android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: 'aarch64-linux-android, x86_64-linux-android, i686-linux-android, armv7-linux-androideabi'
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      working-directory: android
      run: ./gradlew build --no-daemon
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        path: android/build/outputs/apk/*/*.apk
