name: android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
        steps:
    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
    - name: Build
      working-directory: android
      run: ./gradlew build --no-daemon
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        path: android/build/outputs/apk/*/*.apk
