name: web

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: 'wasm32-unknown-unknown'
    - name: Set up wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: |
        (cd crates/renderer-web && wasm-pack build)
        (cd web && npm i && npm run build && tar -C dist -czf ../renderer-web.tar.gz index.html assets)
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        path: renderer-web.tar.gz
