name: x86-64-linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-gnu
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x86-64-linux
        path: target/x86_64-unknown-linux-gnu/release/renderer-desktop
